name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm # enables pnpm store caching based on pnpm-lock.yaml

      # 🔧 GUARANTEED PNPM INSTALL (explicit, no Corepack dependency)
      - name: Install pnpm
        run: |
          set -euxo pipefail
          npm i -g pnpm@10.15.1
          which pnpm
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test -- --passWithNoTests

      - name: Build
        run: pnpm build
